### PR TITLE
Convert website to utf-8

### PR DESCRIPTION
**Pull request by techtonik**
Web is `utf-8`. Chrome even removed encoding switch support.

    $ ../FarManager/enc/tools/contrib/techtonik/rucheck.py
    ./site/common.php - 21 russian (cp1251) symbols
    ./site/getlang.php - 16 russian (cp1251) symbols
    ./site/history/far130b.html - 689 russian (cp1251) symbols
    ./site/inc/common.en.php - 49 russian (cp1251) symbols
    ./site/inc/problems.ru.php - 3523 russian (cp1251) symbols
    ./site/inc/links.ru.php - 112 russian (cp1251) symbols
    ./site/inc/opensource.ru.php - 218 russian (cp1251) symbols
    ./site/inc/download.ru.php - 120 russian (cp1251) symbols
    ./site/inc/common.ru.php - 124 russian (cp1251) symbols
    ./site/inc/plugins.ru.php - 1908 russian (cp1251) symbols
    ./site/inc/index.ru.php - 767 russian (cp1251) symbols
    ./site/inc/license.ru.php - 40 russian (cp1251) symbols
    ./site/inc/news.ru.php - 356 russian (cp1251) symbols
    ./site/inc/screenshots.ru.php - 324 russian (cp1251) symbols

    $ ../FarManager/enc/tools/contrib/techtonik/rucheck.py . | cut -f1 -d' ' | xargs -L1 -I % iconv -f windows-1251 -t utf-8 -o % %

### CODE REVIEW

**Comment by techtonik** [comment]
@trexinc review plz.

**Comment by alabuzhev** [comment]
@techtonik, the site has been converted to utf-8 in f8c7b194711b6610489a11084093b4a4ee01d8b9.
Do we still need this PR or it's ok to close it?

**Comment by techtonik** [comment]
@alabuzhev need to make a few fixes to my windows-1251/cp1251 detector to say for sure. Right now it also triggers on `utf-8` strings.

**Comment by techtonik** [comment]
Yes. The website is converted.

https://github.com/FarGroup/FarManager/pull/278

```
$ python ../FarManager/enc/tools/contrib/techtonik/rucheck.py .
$
```

**Pull request closed without merging**
